-- ============================================================
-- STEP 1: Verify admin user ID
-- ============================================================
SELECT id FROM users WHERE email='admin@gmail.com';

-- ============================================================
-- STEP 2: INSERT 20 PROPERTIES (user_id=1)
-- ============================================================
INSERT INTO properties (title, address, wifi_name, wifi_password, brand_display_name, brand_contact_label, default_host_phone, default_smart_lock_code, default_arrival_tips, default_parking_info, default_emergency_info, default_rules_summary, default_garbage_recycling, default_appliances_notes, default_safety_notes, default_checkout_list, user_id, created_at, updated_at) VALUES
('Sunset Balcony Apartment','12 River Terrace, Kangaroo Point QLD 4169','SunsetWifi','sunny2024','Sunset Stays','Host Contact','+61412345001','4521','Park on River Terrace, buzzer 12','Street parking available on River Terrace','Call 000 for emergencies','No smoking, no parties, quiet after 10pm','Bins on Tuesday morning','Washing machine in laundry, dryer on rack','Smoke alarm tested monthly','Strip beds, leave towels in bath, lock up',1,datetime('now','-18 days'),datetime('now','-18 days')),
('New Farm Garden Studio','8 Brunswick Street, New Farm QLD 4005','NewFarmGuest','garden99','New Farm Escapes','Host','+61412345002','8833','Entry via side gate, key in lockbox','No onsite parking, James Street carpark nearby','Emergency contacts on fridge','Respect neighbours, no shoes inside','Bins Wednesday','Nespresso on bench, pods in drawer','Check stove off before leaving','Dishes done, rubbish out, windows locked',1,datetime('now','-17 days'),datetime('now','-17 days')),
('West End Terrace House','45 Vulture Street, West End QLD 4101','WestEndHome','terrace55','West End Stays','Contact Host','+61412345003','1122','Front door code 1122, park on Vulture St','Driveway available for 1 car','Noosa Rd Medical Centre 5 min away','No events, max 4 guests','Bins Friday','BBQ on deck, propane in cupboard','First aid kit under bathroom sink','BBQ cleaned, all doors locked, keys in box',1,datetime('now','-16 days'),datetime('now','-16 days')),
('Fortitude Valley Loft','22 Ann Street, Fortitude Valley QLD 4006','ValleyLoft','loft2024','Valley Loft Co','Host Line','+61412345004','9944','Intercom unit 22, lift to level 3','Wilson carpark on Brunswick St','Building security: 1800 123 456','Quiet hours 10pm-8am, no smoking','Bins in basement Tuesday','Induction cooktop, instructions on bench','Building has 24hr security','Checkout 10am, keys in dropbox lobby',1,datetime('now','-15 days'),datetime('now','-15 days')),
('Paddington Cottage','67 Given Terrace, Paddington QLD 4064','PaddoWifi','cottage77','Paddington Escapes','Host','+61412345005','3377','Park on Given Tce, front door key under mat','Street parking only','PA Hospital 10 min drive','No parties, be considerate of neighbours','Bins Monday','Vintage stove - gas, matches in drawer','Carbon monoxide alarm in kitchen','Sweep deck, empty bins, return key to mat',1,datetime('now','-14 days'),datetime('now','-14 days')),
('South Bank Studio','3 Melbourne Street, South Brisbane QLD 4101','SouthBankGuest','studio88','South Bank Stays','Contact','+61412345006','6611','Buzz apartment 3, level 2','QPAC carpark 3 min walk','Mater Hospital nearby','No smoking, no pets','Bins Wednesday in basement','Smart TV with Netflix, password on card','Balcony door auto-locks','Keys in lockbox code 6611, strip beds',1,datetime('now','-13 days'),datetime('now','-13 days')),
('Teneriffe Warehouse Apt','101 Vernon Terrace, Teneriffe QLD 4005','TeneriffeCo','ware2024','Teneriffe Living','Host Direct','+61412345007','2288','Industrial lift to level 1, code 2288','Limited street parking on Vernon Tce','Mater Private 10 min','Respect building, no loud music after 9pm','Bins Thursday','Bosch appliances, manuals in folder','Secure building, fob access only','Fob on hook, towels in basket, lock deadbolt',1,datetime('now','-12 days'),datetime('now','-12 days')),
('Highgate Hill Retreat','19 Dornoch Terrace, Highgate Hill QLD 4101','HillWifi','retreat44','Hill Retreats','Host','+61412345008','5566','Steep driveway, park at top','Driveway fits 2 cars','Wesley Hospital 8 min','Quiet property, families welcome','Bins Monday','Slow combustion heater in lounge','Pool fenced, children supervised','Pool cover on, windows latched, bins out',1,datetime('now','-11 days'),datetime('now','-11 days')),
('Bulimba Riverside Home','55 Oxford Street, Bulimba QLD 4171','BulimbaNet','river2024','Bulimba Stays','Host Line','+61412345009','7733','Gate code 7733, park in garage','Single garage included','Mater Hospital 15 min','Family friendly, no smoking','Bins Tuesday','Weber BBQ on deck, gas connected','Life jackets in shed near river','Kayaks locked, gate latched, bins out',1,datetime('now','-10 days'),datetime('now','-10 days')),
('Ascot Heritage Home','14 Racecourse Road, Ascot QLD 4007','AscotGuest','heritage11','Ascot Heritage','Contact Host','+61412345010','4488','Lockbox left of front door, code 4488','Double garage, remote in kitchen drawer','Prince Charles Hospital nearby','Formal property, shoes off at door','Bins Friday','Miele appliances, dishwasher tablets under sink','Security system armed at night','Alarm off code 0000, bins Friday, lock garage',1,datetime('now','-9 days'),datetime('now','-9 days')),
('Milton Rooftop Apartment','8 Park Road, Milton QLD 4064','MiltonTop','roof2024','Milton Sky Stays','Host','+61412345011','3399','Lift to level 5, rooftop access via stairs','Wilson Parking on Park Rd','RBWH 10 min drive','No parties, rooftop shared with residents','Bins Wednesday basement','Rooftop BBQ shared, book via app','Rooftop pool supervised hours only','Pool towels in cupboard, log out of rooftop app',1,datetime('now','-8 days'),datetime('now','-8 days')),
('Woolloongabba Terrace','33 Ipswich Road, Woolloongabba QLD 4102','GabbaWifi','terrace22','Gabba Stays','Host Direct','+61412345012','6677','Street entry, key lockbox right of door','Street parking on Ipswich Rd','PA Hospital 5 min walk','Stadium nearby - no event gatherings','Bins Thursday','Gas cooktop, matches in drawer','Smoke detector in each room','All windows locked, bins out, key in lockbox',1,datetime('now','-7 days'),datetime('now','-7 days')),
('Spring Hill Apartment','77 Leichhardt Street, Spring Hill QLD 4000','SpringHillNet','apt2024','Spring Hill Suites','Contact','+61412345013','1199','Intercom 77, level 4, lift in lobby','Secure basement parking bay 14','City emergency: 000','CBD adjacent - quiet hours strictly 10pm','Bins Tuesday in basement','City views, telescope on balcony','Deadbolt always locked when out','Bay 14 vacated, fob on bench, deadbolt on',1,datetime('now','-6 days'),datetime('now','-6 days')),
('Morningside Family Home','25 Beaudesert Road, Morningside QLD 4170','MorningSideHome','family55','Morningside Stays','Host','+61412345014','8822','Front door lockbox, code 8822','Double driveway, fits 3 cars','Mater Hospital 12 min','Family home, children welcome, no smoking','Bins Monday','Fully equipped kitchen, all appliances','Backyard pool, fenced and gated','Pool cover on, gate latched, keys in lockbox',1,datetime('now','-5 days'),datetime('now','-5 days')),
('Toowong River View','11 Sylvan Road, Toowong QLD 4066','ToowongRiver','river77','River View Stays','Host Line','+61412345015','5544','Gate code 5544, park in driveway','Single driveway included','PA Hospital 15 min','No shoes inside, no smoking','Bins Wednesday','River views from deck, binoculars provided','Deck balustrade checked monthly','Binoculars in drawer, deck chairs stacked, bins out',1,datetime('now','-4 days'),datetime('now','-4 days')),
('Coorparoo Hideaway','88 Old Cleveland Road, Coorparoo QLD 4151','CoorparooHide','hide2024','Coorparoo Escapes','Contact Host','+61412345016','2211','Side gate entry, lockbox code 2211','Street parking on Old Cleveland Rd','QEII Hospital 10 min','Pets by arrangement only, no smoking','Bins Thursday','Outdoor kitchen with pizza oven','Gas pizza oven - instructions on lid','Pizza oven cooled and covered, bins out',1,datetime('now','-3 days'),datetime('now','-3 days')),
('Nundah Townhouse','5 Station Street, Nundah QLD 4012','NundahTown','town99','Nundah Stays','Host','+61412345017','9988','Front door code 9988, level 1','Tandem garage, 2 cars','Prince Charles Hospital 10 min','No smoking, quiet after 10pm','Bins Friday','3 level townhouse, Foxtel included','Staircase steep, handrail available','Foxtel off, garage doors down, bins out',1,datetime('now','-2 days'),datetime('now','-2 days')),
('Greenslopes Bungalow','42 Juliette Street, Greenslopes QLD 4120','GreenslopesNet','bungalow33','Greenslopes Stays','Host Direct','+61412345018','3344','Key safe left gate post, code 3344','Off-street parking driveway','Greenslopes Private Hospital 5 min walk','Quiet street, families welcome','Bins Tuesday','Vintage bungalow, claw foot bath','Exposed wiring in shed - do not enter','Shed locked, key returned, bins out',1,datetime('now','-1 days'),datetime('now','-1 days')),
('Hamilton Harbourview','19 Harbour Road, Hamilton QLD 4007','HamiltonHarbour','harbour55','Hamilton Escapes','Contact','+61412345019','7722','Secure entry code 7722, level 2 lift','2 car basement parking bays 7 and 8','Prince Charles Hospital 12 min','Dress code for rooftop - smart casual','Bins Wednesday basement','Nespresso, Thermomix, full chef kitchen','CCTV in common areas only','Bays 7+8 vacated, Thermomix cleaned, fob on bench',1,datetime('now','-0 days'),datetime('now','-0 days')),
('Kelvin Grove Urban Apt','33 Musk Avenue, Kelvin Grove QLD 4059','KelvinGroveNet','urban2024','Kelvin Stays','Host','+61412345020','1144','Intercom 33, QUT campus nearby','Street parking on Musk Ave','RBWH 5 min walk','Student area - respect quiet study hours','Bins Thursday','Standing desk and monitors for work stays','Building access fob required after 8pm','Fob on hook, desk cleared, bins out',1,datetime('now','-0 days'),datetime('now','-0 days'));

-- ============================================================
-- STEP 3: INSERT 40 STAYS
-- ============================================================
INSERT INTO welcome_packages (property_id, slug, is_published, guest_first_name, guest_email, guest_phone, guest_count, check_in_date, check_out_date, price_total, status, host_phone, smart_lock_code, arrival_tips, parking_info, emergency_info, rules_summary, garbage_recycling, appliances_notes, safety_notes, checkout_list, auto_send, sent_at, created_at, updated_at) VALUES
((SELECT id FROM properties WHERE title='Sunset Balcony Apartment'),'sunset-james-a1b2c3',1,'James','james@email.com','+61400111001',2,date('now','-18 days'),date('now','-15 days'),450.00,'active','+61412345001','4521','Buzzer 12','Street parking','Call 000','No smoking','Bins Tuesday','Washing machine','Smoke alarm','Strip beds, lock up',1,datetime('now','-19 days'),datetime('now','-19 days'),datetime('now','-19 days')),
((SELECT id FROM properties WHERE title='New Farm Garden Studio'),'newfarm-sarah-d4e5f6',1,'Sarah','sarah@email.com','+61400111002',1,date('now','-17 days'),date('now','-14 days'),380.00,'active','+61412345002','8833','Side gate lockbox','James St carpark','Contacts on fridge','No shoes inside','Bins Wednesday','Nespresso pods','Stove off','Dishes done',1,datetime('now','-18 days'),datetime('now','-18 days'),datetime('now','-18 days')),
((SELECT id FROM properties WHERE title='West End Terrace House'),'westend-miguel-g7h8i9',1,'Miguel','miguel@email.com','+61400111003',3,date('now','-16 days'),date('now','-13 days'),520.00,'active','+61412345003','1122','Code 1122','Driveway 1 car','Medical centre 5 min','No events','Bins Friday','BBQ on deck','First aid under sink','BBQ cleaned',1,datetime('now','-17 days'),datetime('now','-17 days'),datetime('now','-17 days')),
((SELECT id FROM properties WHERE title='Fortitude Valley Loft'),'vallyloft-emma-j1k2l3',1,'Emma','emma@email.com','+61400111004',2,date('now','-15 days'),date('now','-12 days'),490.00,'active','+61412345004','9944','Intercom 22, lift level 3','Wilson carpark','Security 1800 123 456','Quiet 10pm-8am','Bins Tuesday','Induction cooktop','24hr security','Keys in dropbox',1,datetime('now','-16 days'),datetime('now','-16 days'),datetime('now','-16 days')),
((SELECT id FROM properties WHERE title='Paddington Cottage'),'paddington-liam-m4n5o6',1,'Liam','liam@email.com','+61400111005',2,date('now','-14 days'),date('now','-11 days'),420.00,'active','+61412345005','3377','Key under mat','Street parking','PA Hospital 10 min','No parties','Bins Monday','Gas stove','CO alarm','Sweep deck',1,datetime('now','-15 days'),datetime('now','-15 days'),datetime('now','-15 days')),
((SELECT id FROM properties WHERE title='South Bank Studio'),'southbank-olivia-p7q8r9',1,'Olivia','olivia@email.com','+61400111006',1,date('now','-13 days'),date('now','-10 days'),350.00,'active','+61412345006','6611','Buzz apt 3','QPAC carpark','Mater nearby','No smoking','Bins Wednesday','Netflix password','Balcony locks','Lockbox 6611',1,datetime('now','-14 days'),datetime('now','-14 days'),datetime('now','-14 days')),
((SELECT id FROM properties WHERE title='Teneriffe Warehouse Apt'),'teneriffe-noah-s1t2u3',1,'Noah','noah@email.com','+61400111007',4,date('now','-12 days'),date('now','-9 days'),680.00,'active','+61412345007','2288','Lift code 2288','Street parking','Mater Private','No music 9pm','Bins Thursday','Bosch appliances','Fob access','Fob on hook',1,datetime('now','-13 days'),datetime('now','-13 days'),datetime('now','-13 days')),
((SELECT id FROM properties WHERE title='Highgate Hill Retreat'),'highgate-ava-v4w5x6',1,'Ava','ava@email.com','+61400111008',2,date('now','-11 days'),date('now','-8 days'),460.00,'active','+61412345008','5566','Steep driveway','Driveway 2 cars','Wesley 8 min','Quiet families','Bins Monday','Heater lounge','Pool fenced','Pool cover on',1,datetime('now','-12 days'),datetime('now','-12 days'),datetime('now','-12 days')),
((SELECT id FROM properties WHERE title='Bulimba Riverside Home'),'bulimba-ethan-y7z8a9',1,'Ethan','ethan@email.com','+61400111009',3,date('now','-10 days'),date('now','-7 days'),580.00,'active','+61412345009','7733','Gate 7733','Single garage','Mater 15 min','Family, no smoke','Bins Tuesday','Weber BBQ','Life jackets shed','Kayaks locked',1,datetime('now','-11 days'),datetime('now','-11 days'),datetime('now','-11 days')),
((SELECT id FROM properties WHERE title='Ascot Heritage Home'),'ascot-isabella-b1c2d3',1,'Isabella','isabella@email.com','+61400111010',2,date('now','-9 days'),date('now','-6 days'),520.00,'active','+61412345010','4488','Lockbox front door','Double garage','Prince Charles','Shoes off','Bins Friday','Miele appliances','Security night','Alarm 0000',1,datetime('now','-10 days'),datetime('now','-10 days'),datetime('now','-10 days')),
((SELECT id FROM properties WHERE title='Milton Rooftop Apartment'),'milton-mason-e4f5g6',1,'Mason','mason@email.com','+61400111011',2,date('now','-2 days'),date('now','+3 days'),490.00,'active','+61412345011','3399','Lift level 5','Wilson Parking','RBWH 10 min','No parties','Bins Wednesday','Rooftop BBQ app','Pool supervised','Log out app',1,datetime('now','-3 days'),datetime('now','-3 days'),datetime('now','-3 days')),
((SELECT id FROM properties WHERE title='Woolloongabba Terrace'),'gabba-sophia-h7i8j9',1,'Sophia','sophia@email.com','+61400111012',1,date('now','-1 days'),date('now','+2 days'),320.00,'active','+61412345012','6677','Lockbox right door','Street parking','PA Hospital 5 min','No gatherings','Bins Thursday','Gas cooktop','Smoke detectors','Windows locked',1,datetime('now','-2 days'),datetime('now','-2 days'),datetime('now','-2 days')),
((SELECT id FROM properties WHERE title='Spring Hill Apartment'),'springhill-william-k1l2m3',1,'William','william@email.com','+61400111013',2,date('now','-1 days'),date('now','+4 days'),560.00,'active','+61412345013','1199','Intercom 77 level 4','Bay 14 basement','City 000','Quiet 10pm','Bins Tuesday','Telescope balcony','Deadbolt out','Bay 14, deadbolt',1,datetime('now','-2 days'),datetime('now','-2 days'),datetime('now','-2 days')),
((SELECT id FROM properties WHERE title='Morningside Family Home'),'morningside-charlotte-n4o5p6',1,'Charlotte','charlotte@email.com','+61400111014',4,date('now','-0 days'),date('now','+5 days'),720.00,'active','+61412345014','8822','Lockbox 8822','Double driveway','Mater 12 min','No smoking','Bins Monday','Full kitchen','Pool fenced','Pool cover on',1,datetime('now','-1 days'),datetime('now','-1 days'),datetime('now','-1 days')),
((SELECT id FROM properties WHERE title='Toowong River View'),'toowong-henry-q7r8s9',1,'Henry','henry@email.com','+61400111015',2,date('now','+1 days'),date('now','+4 days'),440.00,'active','+61412345015','5544','Gate 5544','Single driveway','PA Hospital 15 min','No shoes','Bins Wednesday','Binoculars deck','Deck checked','Binoculars drawer',1,datetime('now','-1 days'),datetime('now','-1 days'),datetime('now','-1 days')),
((SELECT id FROM properties WHERE title='Coorparoo Hideaway'),'coorparoo-amelia-t1u2v3',1,'Amelia','amelia@email.com','+61400111016',3,date('now','+2 days'),date('now','+5 days'),530.00,'active','+61412345016','2211','Side gate 2211','Street parking','QEII 10 min','No smoking','Bins Thursday','Pizza oven','Gas instructions','Oven cooled',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Nundah Townhouse'),'nundah-alexander-w4x5y6',1,'Alexander','alexander@email.com','+61400111017',2,date('now','+3 days'),date('now','+6 days'),410.00,'active','+61412345017','9988','Code 9988','Tandem garage','Prince Charles','Quiet 10pm','Bins Friday','Foxtel','Steep stairs','Foxtel off',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Greenslopes Bungalow'),'greenslopes-mia-z7a8b9',1,'Mia','mia@email.com','+61400111018',1,date('now','+4 days'),date('now','+7 days'),360.00,'active','+61412345018','3344','Key safe 3344','Off-street','Greenslopes 5 min','Quiet families','Bins Tuesday','Claw foot bath','Shed danger','Shed locked',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Hamilton Harbourview'),'hamilton-benjamin-c1d2e3',1,'Benjamin','benjamin@email.com','+61400111019',2,date('now','+5 days'),date('now','+8 days'),620.00,'active','+61412345019','7722','Code 7722 level 2','Bays 7 and 8','Prince Charles','Smart casual','Bins Wednesday','Thermomix Nespresso','CCTV common','Bays vacated',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Kelvin Grove Urban Apt'),'kelvingrove-evelyn-f4g5h6',1,'Evelyn','evelyn@email.com','+61400111020',1,date('now','+6 days'),date('now','+9 days'),330.00,'active','+61412345020','1144','Intercom 33','Street parking','RBWH 5 min','Quiet study','Bins Thursday','Desk monitors','Fob after 8pm','Fob on hook',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Sunset Balcony Apartment'),'sunset-harper-i7j8k9',1,'Harper','harper@email.com','+61400111021',2,date('now','+7 days'),date('now','+10 days'),450.00,'active','+61412345001','4521','Buzzer 12','Street parking','Call 000','No smoking','Bins Tuesday','Washing machine','Smoke alarm','Strip beds',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='New Farm Garden Studio'),'newfarm-lucas-l1m2n3',1,'Lucas','lucas@email.com','+61400111022',1,date('now','+8 days'),date('now','+11 days'),380.00,'active','+61412345002','8833','Side gate lockbox','James St carpark','Contacts on fridge','No shoes','Bins Wednesday','Nespresso','Stove off','Dishes done',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='West End Terrace House'),'westend-ella-o4p5q6',1,'Ella','ella@email.com','+61400111023',4,date('now','+2 days'),date('now','+6 days'),600.00,'active','+61412345003','1122','Code 1122','Driveway 1 car','Medical 5 min','No events','Bins Friday','BBQ deck','First aid','BBQ cleaned',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Fortitude Valley Loft'),'valley-aiden-r7s8t9',1,'Aiden','aiden@email.com','+61400111024',2,date('now','+9 days'),date('now','+12 days'),490.00,'active','+61412345004','9944','Intercom 22','Wilson carpark','Security 1800','Quiet hours','Bins Tuesday','Induction','24hr security','Keys dropbox',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Paddington Cottage'),'paddington-scarlett-u1v2w3',1,'Scarlett','scarlett@email.com','+61400111025',2,date('now','+10 days'),date('now','+13 days'),420.00,'active','+61412345005','3377','Key under mat','Street parking','PA Hospital','No parties','Bins Monday','Gas stove','CO alarm','Sweep deck',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='South Bank Studio'),'southbank-jackson-x4y5z6',1,'Jackson','jackson@email.com','+61400111026',1,date('now','+11 days'),date('now','+14 days'),350.00,'active','+61412345006','6611','Buzz apt 3','QPAC carpark','Mater nearby','No smoking','Bins Wednesday','Netflix','Balcony locks','Lockbox 6611',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Teneriffe Warehouse Apt'),'teneriffe-grace-a7b8c9',1,'Grace','grace@email.com','+61400111027',3,date('now','+12 days'),date('now','+15 days'),610.00,'active','+61412345007','2288','Lift 2288','Street parking','Mater Private','No music 9pm','Bins Thursday','Bosch','Fob access','Fob hook',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Highgate Hill Retreat'),'highgate-owen-d1e2f3',1,'Owen','owen@email.com','+61400111028',2,date('now','+3 days'),date('now','+7 days'),460.00,'active','+61412345008','5566','Steep driveway','2 cars','Wesley 8 min','Quiet families','Bins Monday','Heater','Pool fenced','Pool cover',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Bulimba Riverside Home'),'bulimba-chloe-g4h5i6',1,'Chloe','chloe@email.com','+61400111029',4,date('now','+13 days'),date('now','+16 days'),650.00,'active','+61412345009','7733','Gate 7733','Garage','Mater 15 min','Family','Bins Tuesday','Weber BBQ','Life jackets','Kayaks locked',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Ascot Heritage Home'),'ascot-ryan-j7k8l9',1,'Ryan','ryan@email.com','+61400111030',2,date('now','+14 days'),date('now','+17 days'),520.00,'active','+61412345010','4488','Lockbox front','Double garage','Prince Charles','Shoes off','Bins Friday','Miele','Security','Alarm 0000',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Milton Rooftop Apartment'),'milton-zoey-m1n2o3',1,'Zoey','zoey@email.com','+61400111031',2,date('now','+6 days'),date('now','+9 days'),490.00,'active','+61412345011','3399','Lift level 5','Wilson Parking','RBWH 10 min','No parties','Bins Wednesday','Rooftop BBQ','Pool supervised','Log out',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Woolloongabba Terrace'),'gabba-leo-p4q5r6',1,'Leo','leo@email.com','+61400111032',1,date('now','+15 days'),date('now','+18 days'),320.00,'active','+61412345012','6677','Lockbox right','Street parking','PA Hospital','No gatherings','Bins Thursday','Gas cooktop','Detectors','Windows locked',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Spring Hill Apartment'),'springhill-nora-s7t8u9',1,'Nora','nora@email.com','+61400111033',2,date('now','+16 days'),date('now','+19 days'),560.00,'active','+61412345013','1199','Intercom 77','Bay 14','City 000','Quiet 10pm','Bins Tuesday','Telescope','Deadbolt','Bay 14 out',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Morningside Family Home'),'morningside-caleb-v1w2x3',1,'Caleb','caleb@email.com','+61400111034',5,date('now','+8 days'),date('now','+12 days'),800.00,'active','+61412345014','8822','Lockbox 8822','Double driveway','Mater 12 min','No smoking','Bins Monday','Full kitchen','Pool fenced','Pool cover',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Toowong River View'),'toowong-lillian-y4z5a6',1,'Lillian','lillian@email.com','+61400111035',2,date('now','+17 days'),date('now','+20 days'),440.00,'active','+61412345015','5544','Gate 5544','Single driveway','PA Hospital','No shoes','Bins Wednesday','Binoculars','Deck checked','Binoculars out',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Coorparoo Hideaway'),'coorparoo-samuel-b7c8d9',1,'Samuel','samuel@email.com','+61400111036',3,date('now','+9 days'),date('now','+13 days'),530.00,'active','+61412345016','2211','Side gate 2211','Street parking','QEII 10 min','No smoking','Bins Thursday','Pizza oven','Gas instructions','Oven cooled',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Nundah Townhouse'),'nundah-violet-e1f2g3',1,'Violet','violet@email.com','+61400111037',2,date('now','+18 days'),date('now','+21 days'),410.00,'active','+61412345017','9988','Code 9988','Tandem garage','Prince Charles','Quiet 10pm','Bins Friday','Foxtel','Steep stairs','Foxtel off',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Greenslopes Bungalow'),'greenslopes-julian-h4i5j6',1,'Julian','julian@email.com','+61400111038',1,date('now','+11 days'),date('now','+14 days'),360.00,'active','+61412345018','3344','Key safe 3344','Off-street','Greenslopes 5 min','Quiet','Bins Tuesday','Claw foot bath','Shed danger','Shed locked',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Hamilton Harbourview'),'hamilton-aurora-k7l8m9',1,'Aurora','aurora@email.com','+61400111039',2,date('now','+19 days'),date('now','+22 days'),620.00,'active','+61412345019','7722','Code 7722','Bays 7 and 8','Prince Charles','Smart casual','Bins Wednesday','Thermomix','CCTV common','Bays vacated',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days')),
((SELECT id FROM properties WHERE title='Kelvin Grove Urban Apt'),'kelvingrove-dominic-n1o2p3',1,'Dominic','dominic@email.com','+61400111040',2,date('now','+20 days'),date('now','+23 days'),380.00,'active','+61412345020','1144','Intercom 33','Street parking','RBWH 5 min','Quiet study','Bins Thursday','Desk monitors','Fob after 8pm','Fob on hook',1,datetime('now','-0 days'),datetime('now','-0 days'),datetime('now','-0 days'));

-- ============================================================
-- VERIFY
-- ============================================================
SELECT 'Properties: ' || COUNT(*) FROM properties WHERE user_id=1;
SELECT 'Stays: ' || COUNT(*) FROM welcome_packages;
